export const FETCH_MOVIES = 'FETCH_MOVIES';
export const ADD_COMMENT_TO_MOVIE = 'ADD_COMMENT_TO_MOVIE';
export const FETCH_MOVIES_SUCCESS = 'FETCH_MOVIES_SUCCESS';
export const FETCH_MOVIES_ERROR = 'FETCH_MOVIES_ERROR';

export const FETCH_MOVIES_COMPLETION = 'FETCH_MOVIES_COMPLETION';
export const FETCH_MOVIES_COMPLETION_SUCCESS = 'FETCH_MOVIES_COMPLETION_SUCCESS';
export const FETCH_MOVIES_COMPLETION_ERROR = 'FETCH_MOVIES_COMPLETION_ERROR';